### ISSUE TITLE
unknown enum value EnableDebugConsole

### ISSUE THREAD

**Issue by milivojm** [CntoDev/compositions#4] opened 2017-12-02 08:25 UTC
Version: 1.05

1. drag the coop compositions to a map.
2. error message appears.

![20171202084041_1](https://user-images.githubusercontent.com/7799132/33513421-b02e5e2e-d742-11e7-9554-f119be501360.jpg)

**Comment by freghar** [comment] 2017-12-02 12:20
This won't be easy to fix. I looked into it yesterday and all the pieces seem to be there and the functionality is actually working despite the error.

This is caused by https://github.com/CntoDev/compositions/blob/6729c8133b2e3730fa34fea39ca19fb8c5879fe2/reference/Default%2520Modules%2520(Coop)/composition.sqe#L3078 which sets Eden defaults upon placement. (See it in the editor, it's the only "Execute Code (Eden)" module in the composition.

A simpler reproducer is `"Scenario" set3denmissionattribute ["EnableDebugConsole", 1]`.

This is supposed to work according to https://community.bistudio.com/wiki/Eden_Editor:_Setting_Attributes#Setting_Scenario_Attributes and creating a new mission and modifying the attribute manually in Eden and saving the mission indeed produces a valid
```
class CustomAttributes
{
	class Category0
	{
		name="Scenario";
		class Attribute0
		{
			property="EnableDebugConsole";
			expression="true";
			class Value
			{
				class data
				{
					class type
					{
						type[]=
						{
							"SCALAR"
						};
					};
					value=1;
				};
			};
		};
		nAttributes=1;
	};
};
```
and the feature works as expected.

So I have no idea why the error shows up as far as game data is concerned, maybe the attribute was accidentally deleted in the engine. Fortunately, this may already be fixed on devbranch,
> Fixed: Warning messages connected to the set3DENMissionAttribute script command were not correct

**Comment by milivojm** [comment] 2017-12-02 12:47
Let's just close this issue then, it is not our problem and error message is not a problem in itself.

**Comment by freghar** [comment] 2017-12-02 14:05
I would keep it open until (if) it gets fixed on stable. If it doesn't - for some reason - we need to deal with it another way.

**Comment by freghar** [comment] 2017-12-24 15:11
Hotfix 1.80 should have fixed this, https://dev.arma3.com/post/spotrep-00078, please re-test.

**Comment by milivojm** [comment] 2017-12-25 14:56
Issue still present.

**Comment by CNTODachi** [comment] 2018-07-17 08:47
This issue no longer exists and has since been fixed.

**Closed by CNTODachi** 2018-07-17 08:47 UTC
Labels: arma issue
